lvim.autocommands._auto_resize["1"]["1"] = "VimResized"
lvim.autocommands._auto_resize["1"]["2"] = "*"
lvim.autocommands._auto_resize["1"]["3"] = "wincmd ="
lvim.autocommands._buffer_bindings["1"]["1"] = "FileType"
lvim.autocommands._buffer_bindings["1"]["2"] = "floaterm"
lvim.autocommands._buffer_bindings["1"]["3"] = "nnoremap <silent> <buffer> q :q<CR>"
lvim.autocommands._filetypechanges["1"]["1"] = "BufWinEnter"
lvim.autocommands._filetypechanges["1"]["2"] = ".tf"
lvim.autocommands._filetypechanges["1"]["3"] = "setlocal filetype=terraform"
lvim.autocommands._filetypechanges["2"]["1"] = "BufRead"
lvim.autocommands._filetypechanges["2"]["2"] = "*.tf"
lvim.autocommands._filetypechanges["2"]["3"] = "setlocal filetype=terraform"
lvim.autocommands._filetypechanges["3"]["1"] = "BufNewFile"
lvim.autocommands._filetypechanges["3"]["2"] = "*.tf"
lvim.autocommands._filetypechanges["3"]["3"] = "setlocal filetype=terraform"
lvim.autocommands._filetypechanges["4"]["1"] = "BufWinEnter"
lvim.autocommands._filetypechanges["4"]["2"] = ".zsh"
lvim.autocommands._filetypechanges["4"]["3"] = "setlocal filetype=sh"
lvim.autocommands._filetypechanges["5"]["1"] = "BufRead"
lvim.autocommands._filetypechanges["5"]["2"] = "*.zsh"
lvim.autocommands._filetypechanges["5"]["3"] = "setlocal filetype=sh"
lvim.autocommands._filetypechanges["6"]["1"] = "BufNewFile"
lvim.autocommands._filetypechanges["6"]["2"] = "*.zsh"
lvim.autocommands._filetypechanges["6"]["3"] = "setlocal filetype=sh"
lvim.autocommands._general_lsp["1"]["1"] = "FileType"
lvim.autocommands._general_lsp["1"]["2"] = "lspinfo"
lvim.autocommands._general_lsp["1"]["3"] = "nnoremap <silent> <buffer> q :q<CR>"
lvim.autocommands._general_settings["10"]["1"] = "FileType"
lvim.autocommands._general_settings["10"]["2"] = "qf"
lvim.autocommands._general_settings["10"]["3"] = "set nobuflisted"
lvim.autocommands._general_settings["1"]["1"] = "Filetype"
lvim.autocommands._general_settings["1"]["2"] = "*"
lvim.autocommands._general_settings["1"]["3"] = "lua require('utils.ft').do_filetype(vim.fn.expand(\"<amatch>\"))"
lvim.autocommands._general_settings["2"]["1"] = "FileType"
lvim.autocommands._general_settings["2"]["2"] = "qf"
lvim.autocommands._general_settings["2"]["3"] = "nnoremap <silent> <buffer> q :q<CR>"
lvim.autocommands._general_settings["3"]["1"] = "FileType"
lvim.autocommands._general_settings["3"]["2"] = "lsp-installer"
lvim.autocommands._general_settings["3"]["3"] = "nnoremap <silent> <buffer> q :q<CR>"
lvim.autocommands._general_settings["4"]["1"] = "TextYankPost"
lvim.autocommands._general_settings["4"]["2"] = "*"
lvim.autocommands._general_settings["4"]["3"] = "lua require('vim.highlight').on_yank({higroup = 'Search', timeout = 200})"
lvim.autocommands._general_settings["5"]["1"] = "BufWinEnter"
lvim.autocommands._general_settings["5"]["2"] = "*"
lvim.autocommands._general_settings["5"]["3"] = "setlocal formatoptions-=c formatoptions-=r formatoptions-=o"
lvim.autocommands._general_settings["6"]["1"] = "BufWinEnter"
lvim.autocommands._general_settings["6"]["2"] = "dashboard"
lvim.autocommands._general_settings["6"]["3"] = "setlocal cursorline signcolumn=yes cursorcolumn number"
lvim.autocommands._general_settings["7"]["1"] = "BufRead"
lvim.autocommands._general_settings["7"]["2"] = "*"
lvim.autocommands._general_settings["7"]["3"] = "setlocal formatoptions-=c formatoptions-=r formatoptions-=o"
lvim.autocommands._general_settings["8"]["1"] = "BufNewFile"
lvim.autocommands._general_settings["8"]["2"] = "*"
lvim.autocommands._general_settings["8"]["3"] = "setlocal formatoptions-=c formatoptions-=r formatoptions-=o"
lvim.autocommands._general_settings["9"]["1"] = "BufWritePost"
lvim.autocommands._general_settings["9"]["2"] = "/home/crash/.config/lvim/config.lua"
lvim.autocommands._general_settings["9"]["3"] = "lua require('utils').reload_lv_config()"
lvim.autocommands._git["1"]["1"] = "FileType"
lvim.autocommands._git["1"]["2"] = "gitcommit"
lvim.autocommands._git["1"]["3"] = "setlocal wrap"
lvim.autocommands._git["2"]["1"] = "FileType"
lvim.autocommands._git["2"]["2"] = "gitcommit"
lvim.autocommands._git["2"]["3"] = "setlocal spell"
lvim.autocommands._markdown["1"]["1"] = "FileType"
lvim.autocommands._markdown["1"]["2"] = "markdown"
lvim.autocommands._markdown["1"]["3"] = "setlocal wrap"
lvim.autocommands._markdown["2"]["1"] = "FileType"
lvim.autocommands._markdown["2"]["2"] = "markdown"
lvim.autocommands._markdown["2"]["3"] = "setlocal spell"
lvim.autocommands._packer_compile["1"]["1"] = "BufWritePost"
lvim.autocommands._packer_compile["1"]["2"] = "plugins.lua"
lvim.autocommands._packer_compile["1"]["3"] = "PackerCompile"
lvim.builtin.autopairs.active = true
lvim.builtin.autopairs.auto_select = true
lvim.builtin.autopairs.check_ts = true
lvim.builtin.autopairs.insert = false
lvim.builtin.autopairs.map_char.all = "("
lvim.builtin.autopairs.map_char.tex = "{"
lvim.builtin.autopairs.map_complete = true
lvim.builtin.autopairs.map_cr = true
lvim.builtin.autopairs.ts_config.java = false
lvim.builtin.autopairs.ts_config.javascript["1"] = "template_string"
lvim.builtin.autopairs.ts_config.lua["1"] = "string"
lvim.builtin.bufferline.active = true
lvim.builtin.bufferline.keymap.normal_mode["<S-h>"] = ":BufferPrevious<CR>"
lvim.builtin.bufferline.keymap.normal_mode["<S-l>"] = ":BufferNext<CR>"
lvim.builtin.cmp.confirm_opts.behavior = "replace"
lvim.builtin.cmp.confirm_opts.select = true
lvim.builtin.cmp.documentation.border["1"] = "╭"
lvim.builtin.cmp.documentation.border["2"] = "─"
lvim.builtin.cmp.documentation.border["3"] = "╮"
lvim.builtin.cmp.documentation.border["4"] = "│"
lvim.builtin.cmp.documentation.border["5"] = "╯"
lvim.builtin.cmp.documentation.border["6"] = "─"
lvim.builtin.cmp.documentation.border["7"] = "╰"
lvim.builtin.cmp.documentation.border["8"] = "│"
-- lvim.builtin.cmp.formatting.format = function ()
lvim.builtin.cmp.formatting.kind_icons.Class = " "
lvim.builtin.cmp.formatting.kind_icons.Color = " "
lvim.builtin.cmp.formatting.kind_icons.Constant = "ﲀ "
lvim.builtin.cmp.formatting.kind_icons.Constructor = " "
lvim.builtin.cmp.formatting.kind_icons.EnumMember = " "
lvim.builtin.cmp.formatting.kind_icons.Enum = "練"
lvim.builtin.cmp.formatting.kind_icons.Event = " "
lvim.builtin.cmp.formatting.kind_icons.Field = " "
lvim.builtin.cmp.formatting.kind_icons.File = ""
lvim.builtin.cmp.formatting.kind_icons.Folder = " "
lvim.builtin.cmp.formatting.kind_icons.Function = " "
lvim.builtin.cmp.formatting.kind_icons.Interface = "ﰮ "
lvim.builtin.cmp.formatting.kind_icons.Keyword = " "
lvim.builtin.cmp.formatting.kind_icons.Method = " "
lvim.builtin.cmp.formatting.kind_icons.Module = " "
lvim.builtin.cmp.formatting.kind_icons.Operator = ""
lvim.builtin.cmp.formatting.kind_icons.Property = " "
lvim.builtin.cmp.formatting.kind_icons.Reference = " "
lvim.builtin.cmp.formatting.kind_icons.Snippet = " "
lvim.builtin.cmp.formatting.kind_icons.Struct = " "
lvim.builtin.cmp.formatting.kind_icons.Text = " "
lvim.builtin.cmp.formatting.kind_icons.TypeParameter = " "
lvim.builtin.cmp.formatting.kind_icons.Unit = "塞"
lvim.builtin.cmp.formatting.kind_icons.Value = " "
lvim.builtin.cmp.formatting.kind_icons.Variable = " "
-- lvim.builtin.cmp.mapping["<C-d>"] = function ()
-- lvim.builtin.cmp.mapping["<C-e>"] = function ()
-- lvim.builtin.cmp.mapping["<C-f>"] = function ()
-- lvim.builtin.cmp.mapping["<CR>"].invoke = function ()
lvim.builtin.cmp.mapping["<CR>"].modes["1"] = "i"
-- lvim.builtin.cmp.mapping["<C-Space>"] = function ()
-- lvim.builtin.cmp.mapping["<S-Tab>"].invoke = function ()
lvim.builtin.cmp.mapping["<S-Tab>"].modes["1"] = "i"
lvim.builtin.cmp.mapping["<S-Tab>"].modes["2"] = "s"
-- lvim.builtin.cmp.mapping["<Tab>"].invoke = function ()
lvim.builtin.cmp.mapping["<Tab>"].modes["1"] = "i"
lvim.builtin.cmp.mapping["<Tab>"].modes["2"] = "s"
-- lvim.builtin.cmp.snippet.expand = function ()
lvim.builtin.cmp.sources["10"].name = "crates"
lvim.builtin.cmp.sources["1"].name = "nvim_lsp"
lvim.builtin.cmp.sources["2"].name = "path"
lvim.builtin.cmp.sources["3"].name = "luasnip"
lvim.builtin.cmp.sources["4"].name = "cmp_tabnine"
lvim.builtin.cmp.sources["5"].name = "nvim_lua"
lvim.builtin.cmp.sources["6"].name = "buffer"
lvim.builtin.cmp.sources["7"].name = "calc"
lvim.builtin.cmp.sources["8"].name = "emoji"
lvim.builtin.cmp.sources["9"].name = "treesitter"
lvim.builtin.comment.active = true
lvim.builtin.comment.comment_empty = false
lvim.builtin.comment.create_mappings = true
lvim.builtin.comment.line_mapping = "gcc"
lvim.builtin.comment.marker_padding = true
lvim.builtin.comment.operator_mapping = "gc"
lvim.builtin.dap.active = true
lvim.builtin.dap.breakpoint.linehl = ""
lvim.builtin.dap.breakpoint.numhl = ""
lvim.builtin.dap.breakpoint_rejected.linehl = ""
lvim.builtin.dap.breakpoint_rejected.numhl = ""
lvim.builtin.dap.breakpoint_rejected.text = ""
lvim.builtin.dap.breakpoint_rejected.texthl = "LspDiagnosticsSignHint"
lvim.builtin.dap.breakpoint.text = ""
lvim.builtin.dap.breakpoint.texthl = "LspDiagnosticsSignError"
lvim.builtin.dap.stopped.linehl = "DiagnosticUnderlineInfo"
lvim.builtin.dap.stopped.numhl = "LspDiagnosticsSignInformation"
lvim.builtin.dap.stopped.text = ""
lvim.builtin.dap.stopped.texthl = "LspDiagnosticsSignInformation"
lvim.builtin.dashboard.active = true
lvim.builtin.dashboard.custom_header["1"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⣀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["10"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠈⠁⠒⠤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["11"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣇⠀⠀⠀⠀⠀⠀⠉⠢⠤⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡟⠈⠑⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["12"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠑⠒⠤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡇⠀⠀⢀⣣⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["13"] = "⠀⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠒⠢⠤⠄⣀⣀⠀⠀⠀⢠⣿⡟⠀⠀⠀⣺⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["14"] = "⠀⣿⠇⠀⠀⠀⠀⠀⣤⡄⠀⠀⢠⣤⡄⠀⢨⣭⣠⣤⣤⣤⡀⠀⠀⢀⣤⣤⣤⣤⡄⠀⠀⠀⣤⣄⣤⣤⣤⠀⠀⣿⣯⠉⠉⣿⡟⠀⠈⢩⣭⣤⣤⠀⠀⠀⠀⣠⣤⣤⣤⣄⣤⣤"
lvim.builtin.dashboard.custom_header["15"] = "⢠⣿⠀⠀⠀⠀⠀⠀⣿⠃⠀⠀⣸⣿⠁⠀⣿⣿⠉⠀⠈⣿⡇⠀⠀⠛⠋⠀⠀⢹⣿⠀⠀⠀⣿⠏⠀⠸⠿⠃⠀⣿⣿⠀⣰⡟⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⣿⡟⢸⣿⡇⢀⣿"
lvim.builtin.dashboard.custom_header["16"] = "⣸⡇⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⣿⡟⠀⢠⣿⡇⠀⠀⢰⣿⡇⠀⣰⣾⠟⠛⠛⣻⡇⠀⠀⢸⡿⠀⠀⠀⠀⠀⠀⢻⣿⢰⣿⠀⠀⠀⠀⠀⠀⣾⡇⠀⠀⠀⢸⣿⠇⢸⣿⠀⢸⡏"
lvim.builtin.dashboard.custom_header["17"] = "⣿⣧⣤⣤⣤⡄⠀⠘⣿⣤⣤⡤⣿⠇⠀⢸⣿⠁⠀⠀⣼⣿⠀⠀⢿⣿⣤⣤⠔⣿⠃⠀⠀⣾⡇⠀⠀⠀⠀⠀⠀⢸⣿⣿⠋⠀⠀⠀⢠⣤⣤⣿⣥⣤⡄⠀⣼⣿⠀⣸⡏⠀⣿⠃"
lvim.builtin.dashboard.custom_header["18"] = "⠉⠉⠉⠉⠉⠁⠀⠀⠈⠉⠉⠀⠉⠀⠀⠈⠉⠀⠀⠀⠉⠉⠀⠀⠀⠉⠉⠁⠈⠉⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠁⠀⠉⠁⠀⠉⠁⠀⠉⠀"
lvim.builtin.dashboard.custom_header["2"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣶⣾⠿⠿⠟⠛⠛⠛⠛⠿⠿⣿⣷⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["3"] = "  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⡿⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠿⣷⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["4"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⡿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["5"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠒⠂⠉⠉⠉⠉⢩⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["6"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠸⡀⠀⠀⠀⠀⠀⢰⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["7"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠠⡀⠀⠀⢀⣾⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["8"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠢⢀⣸⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_header["9"] = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡧⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
lvim.builtin.dashboard.custom_section.a.command = "Telescope find_files"
lvim.builtin.dashboard.custom_section.a.description["1"] = "  Find File          "
lvim.builtin.dashboard.custom_section.b.command = "Telescope projects"
lvim.builtin.dashboard.custom_section.b.description["1"] = "  Recent Projects    "
lvim.builtin.dashboard.custom_section.c.command = "Telescope oldfiles"
lvim.builtin.dashboard.custom_section.c.description["1"] = "  Recently Used Files"
lvim.builtin.dashboard.custom_section.d.command = "Telescope live_grep"
lvim.builtin.dashboard.custom_section.d.description["1"] = "  Find Word          "
lvim.builtin.dashboard.custom_section.e.command = ":e /home/crash/.config/lvim/config.lua"
lvim.builtin.dashboard.custom_section.e.description["1"] = "  Configuration      "
lvim.builtin.dashboard.disable_at_vim_enter = 0
lvim.builtin.dashboard.footer["1"] = "lunarvim.org"
lvim.builtin.dashboard.search_handler = "telescope"
lvim.builtin.dashboard.session_directory = "/home/crash/.cache/nvim/sessions"
lvim.builtin.gitsigns.active = true
lvim.builtin.gitsigns.opts.keymaps.buffer = true
lvim.builtin.gitsigns.opts.keymaps.noremap = true
lvim.builtin.gitsigns.opts.linehl = false
lvim.builtin.gitsigns.opts.numhl = false
lvim.builtin.gitsigns.opts.sign_priority = 6
lvim.builtin.gitsigns.opts.signs.add.hl = "GitSignsAdd"
lvim.builtin.gitsigns.opts.signs.add.linehl = "GitSignsAddLn"
lvim.builtin.gitsigns.opts.signs.add.numhl = "GitSignsAddNr"
lvim.builtin.gitsigns.opts.signs.add.text = "▎"
lvim.builtin.gitsigns.opts.signs.changedelete.hl = "GitSignsChange"
lvim.builtin.gitsigns.opts.signs.changedelete.linehl = "GitSignsChangeLn"
lvim.builtin.gitsigns.opts.signs.changedelete.numhl = "GitSignsChangeNr"
lvim.builtin.gitsigns.opts.signs.changedelete.text = "▎"
lvim.builtin.gitsigns.opts.signs.change.hl = "GitSignsChange"
lvim.builtin.gitsigns.opts.signs.change.linehl = "GitSignsChangeLn"
lvim.builtin.gitsigns.opts.signs.change.numhl = "GitSignsChangeNr"
lvim.builtin.gitsigns.opts.signs.change.text = "▎"
lvim.builtin.gitsigns.opts.signs.delete.hl = "GitSignsDelete"
lvim.builtin.gitsigns.opts.signs.delete.linehl = "GitSignsDeleteLn"
lvim.builtin.gitsigns.opts.signs.delete.numhl = "GitSignsDeleteNr"
lvim.builtin.gitsigns.opts.signs.delete.text = "契"
lvim.builtin.gitsigns.opts.signs.topdelete.hl = "GitSignsDelete"
lvim.builtin.gitsigns.opts.signs.topdelete.linehl = "GitSignsDeleteLn"
lvim.builtin.gitsigns.opts.signs.topdelete.numhl = "GitSignsDeleteNr"
lvim.builtin.gitsigns.opts.signs.topdelete.text = "契"
lvim.builtin.gitsigns.opts.update_debounce = 200
lvim.builtin.gitsigns.opts.watch_gitdir.interval = 1000
lvim.builtin.lualine.active = true
lvim.builtin.lualine.extensions["1"] = "nvim-tree"
lvim.builtin.lualine.inactive_sections.lualine_a["1"] = "filename"
lvim.builtin.lualine.options.component_separators.left = ""
lvim.builtin.lualine.options.component_separators.right = ""
lvim.builtin.lualine.options.disabled_filetypes["1"] = "dashboard"
lvim.builtin.lualine.options.disabled_filetypes["2"] = "NvimTree"
lvim.builtin.lualine.options.disabled_filetypes["3"] = "Outline"
lvim.builtin.lualine.options.icons_enabled = true
lvim.builtin.lualine.options.section_separators.left = ""
lvim.builtin.lualine.options.section_separators.right = ""
lvim.builtin.lualine.options.theme = "onedarker"
-- lvim.builtin.lualine.sections.lualine_a["1"]["1"] = function ()
lvim.builtin.lualine.sections.lualine_a["1"].padding.left = 0
lvim.builtin.lualine.sections.lualine_a["1"].padding.right = 0
lvim.builtin.lualine.sections.lualine_b["1"]["1"] = "b:gitsigns_head"
lvim.builtin.lualine.sections.lualine_b["1"].color.gui = "bold"
-- lvim.builtin.lualine.sections.lualine_b["1"].cond = function ()
lvim.builtin.lualine.sections.lualine_b["1"].icon = " "
lvim.builtin.lualine.sections.lualine_b["2"]["1"] = "filename"
lvim.builtin.lualine.sections.lualine_c["1"]["1"] = "diff"
lvim.builtin.lualine.sections.lualine_c["1"].diff_color.added.fg = "#98be65"
lvim.builtin.lualine.sections.lualine_c["1"].diff_color.modified.fg = "#ECBE7B"
lvim.builtin.lualine.sections.lualine_c["1"].diff_color.removed.fg = "#ec5f67"
-- lvim.builtin.lualine.sections.lualine_c["1"].source = function ()
lvim.builtin.lualine.sections.lualine_c["1"].symbols.added = "  "
lvim.builtin.lualine.sections.lualine_c["1"].symbols.modified = "柳"
lvim.builtin.lualine.sections.lualine_c["1"].symbols.removed = " "
-- lvim.builtin.lualine.sections.lualine_c["2"]["1"] = function ()
lvim.builtin.lualine.sections.lualine_c["2"].color.fg = "#98be65"
-- lvim.builtin.lualine.sections.lualine_c["2"].cond = function ()
lvim.builtin.lualine.sections.lualine_x["1"]["1"] = "diagnostics"
-- lvim.builtin.lualine.sections.lualine_x["1"].cond = function ()
lvim.builtin.lualine.sections.lualine_x["1"].sources["1"] = "nvim_lsp"
lvim.builtin.lualine.sections.lualine_x["1"].symbols.error = " "
lvim.builtin.lualine.sections.lualine_x["1"].symbols.hint = " "
lvim.builtin.lualine.sections.lualine_x["1"].symbols.info = " "
lvim.builtin.lualine.sections.lualine_x["1"].symbols.warn = " "
-- lvim.builtin.lualine.sections.lualine_x["2"]["1"] = function ()
lvim.builtin.lualine.sections.lualine_x["2"].color.fg = "#98be65"
-- lvim.builtin.lualine.sections.lualine_x["2"].cond = function ()
-- lvim.builtin.lualine.sections.lualine_x["3"]["1"] = function ()
lvim.builtin.lualine.sections.lualine_x["3"].color.gui = "bold"
-- lvim.builtin.lualine.sections.lualine_x["3"].cond = function ()
lvim.builtin.lualine.sections.lualine_x["3"].icon = " "
lvim.builtin.lualine.sections.lualine_x["4"]["1"] = "filetype"
-- lvim.builtin.lualine.sections.lualine_x["4"].cond = function ()
-- lvim.builtin.lualine.sections.lualine_z["1"]["1"] = function ()
lvim.builtin.lualine.sections.lualine_z["1"].color.bg = "#202328"
lvim.builtin.lualine.sections.lualine_z["1"].color.fg = "#ECBE7B"
lvim.builtin.lualine.sections.lualine_z["1"].padding.left = 0
lvim.builtin.lualine.sections.lualine_z["1"].padding.right = 0
lvim.builtin.lualine.style = "lvim"
lvim.builtin.nvimtree.active = true
lvim.builtin.nvimtree.allow_resize = 1
lvim.builtin.nvimtree.auto_ignore_ft["1"] = "startify"
lvim.builtin.nvimtree.auto_ignore_ft["2"] = "dashboard"
lvim.builtin.nvimtree.git_hl = 1
lvim.builtin.nvimtree.hide_dotfiles = 1
lvim.builtin.nvimtree.icons.default = ""
lvim.builtin.nvimtree.icons.folder.default = ""
lvim.builtin.nvimtree.icons.folder.empty = ""
lvim.builtin.nvimtree.icons.folder.empty_open = ""
lvim.builtin.nvimtree.icons.folder.open = ""
lvim.builtin.nvimtree.icons.folder.symlink = ""
lvim.builtin.nvimtree.icons.git.deleted = ""
lvim.builtin.nvimtree.icons.git.ignored = "◌"
lvim.builtin.nvimtree.icons.git.renamed = "➜"
lvim.builtin.nvimtree.icons.git.staged = "S"
lvim.builtin.nvimtree.icons.git.unmerged = ""
lvim.builtin.nvimtree.icons.git.unstaged = ""
lvim.builtin.nvimtree.icons.git.untracked = "U"
lvim.builtin.nvimtree.icons.symlink = ""
lvim.builtin.nvimtree.ignore["1"] = ".git"
lvim.builtin.nvimtree.ignore["2"] = "node_modules"
lvim.builtin.nvimtree.ignore["3"] = ".cache"
lvim.builtin.nvimtree.quit_on_open = 0
lvim.builtin.nvimtree.respect_buf_cwd = 1
lvim.builtin.nvimtree.root_folder_modifier = ":t"
lvim.builtin.nvimtree.setup.auto_close = 1
lvim.builtin.nvimtree.setup.disable_netrw = 0
lvim.builtin.nvimtree.setup.hijack_netrw = 0
lvim.builtin.nvimtree.setup.lsp_diagnostics = 1
lvim.builtin.nvimtree.setup.open_on_setup = 0
lvim.builtin.nvimtree.setup.open_on_tab = 0
lvim.builtin.nvimtree.setup.update_cwd = 1
lvim.builtin.nvimtree.setup.update_focused_file.enable = 1
lvim.builtin.nvimtree.setup.view.auto_resize = false
lvim.builtin.nvimtree.setup.view.mappings.custom_only = false
lvim.builtin.nvimtree.setup.view.mappings.list["1"].cb = ":lua require'nvim-tree'.on_keypress('edit')<CR>"
lvim.builtin.nvimtree.setup.view.mappings.list["1"].key["1"] = "l"
lvim.builtin.nvimtree.setup.view.mappings.list["1"].key["2"] = "<CR>"
lvim.builtin.nvimtree.setup.view.mappings.list["1"].key["3"] = "o"
lvim.builtin.nvimtree.setup.view.mappings.list["2"].cb = ":lua require'nvim-tree'.on_keypress('close_node')<CR>"
lvim.builtin.nvimtree.setup.view.mappings.list["2"].key = "h"
lvim.builtin.nvimtree.setup.view.mappings.list["3"].cb = ":lua require'nvim-tree'.on_keypress('vsplit')<CR>"
lvim.builtin.nvimtree.setup.view.mappings.list["3"].key = "v"
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.view.width = 30
lvim.builtin.nvimtree.show_icons.files = 1
lvim.builtin.nvimtree.show_icons.folder_arrows = 1
lvim.builtin.nvimtree.show_icons.folders = 1
lvim.builtin.nvimtree.show_icons.git = 0
lvim.builtin.nvimtree.show_icons.tree_width = 30
lvim.builtin.project.active = true
lvim.builtin.project.datapath = "/home/crash/.cache/nvim"
lvim.builtin.project.detection_methods["1"] = "lsp"
lvim.builtin.project.detection_methods["2"] = "pattern"
lvim.builtin.project.manual_mode = false
lvim.builtin.project.patterns["1"] = ".git"
lvim.builtin.project.patterns["2"] = "_darcs"
lvim.builtin.project.patterns["3"] = ".hg"
lvim.builtin.project.patterns["4"] = ".bzr"
lvim.builtin.project.patterns["5"] = ".svn"
lvim.builtin.project.patterns["6"] = "Makefile"
lvim.builtin.project.patterns["7"] = "package.json"
lvim.builtin.project.show_hidden = false
lvim.builtin.project.silent_chdir = true
lvim.builtin.telescope.active = true
lvim.builtin.telescope.defaults.borderchars["1"] = "─"
lvim.builtin.telescope.defaults.borderchars["2"] = "│"
lvim.builtin.telescope.defaults.borderchars["3"] = "─"
lvim.builtin.telescope.defaults.borderchars["4"] = "│"
lvim.builtin.telescope.defaults.borderchars["5"] = "╭"
lvim.builtin.telescope.defaults.borderchars["6"] = "╮"
lvim.builtin.telescope.defaults.borderchars["7"] = "╯"
lvim.builtin.telescope.defaults.borderchars["8"] = "╰"
lvim.builtin.telescope.defaults.color_devicons = true
lvim.builtin.telescope.defaults.entry_prefix = "  "
-- lvim.builtin.telescope.defaults.file_previewer = function ()
-- lvim.builtin.telescope.defaults.file_sorter = function ()
-- lvim.builtin.telescope.defaults.generic_sorter = function ()
-- lvim.builtin.telescope.defaults.grep_previewer = function ()
lvim.builtin.telescope.defaults.initial_mode = "insert"
lvim.builtin.telescope.defaults.layout_config.horizontal.mirror = false
lvim.builtin.telescope.defaults.layout_config.preview_cutoff = 120
lvim.builtin.telescope.defaults.layout_config.prompt_position = "bottom"
lvim.builtin.telescope.defaults.layout_config.vertical.mirror = false
lvim.builtin.telescope.defaults.layout_config.width = 0.75
lvim.builtin.telescope.defaults.layout_strategy = "horizontal"
lvim.builtin.telescope.defaults.mappings.i["<C-c>"]["1"] = "close"
lvim.builtin.telescope.defaults.mappings.i["<C-j>"]["1"] = "cycle_history_next"
lvim.builtin.telescope.defaults.mappings.i["<C-k>"]["1"] = "cycle_history_prev"
lvim.builtin.telescope.defaults.mappings.i["<C-n>"]["1"] = "move_selection_next"
lvim.builtin.telescope.defaults.mappings.i["<C-p>"]["1"] = "move_selection_previous"
lvim.builtin.telescope.defaults.mappings.i["<C-q>"]["1"] = "smart_send_to_qflist"
lvim.builtin.telescope.defaults.mappings.i["<C-q>"]["2"] = "open_qflist"
lvim.builtin.telescope.defaults.mappings.i["<CR>"]["1"] = "select_default"
lvim.builtin.telescope.defaults.mappings.i["<CR>"]["2"] = "center"
lvim.builtin.telescope.defaults.mappings.n["<C-n>"]["1"] = "move_selection_next"
lvim.builtin.telescope.defaults.mappings.n["<C-p>"]["1"] = "move_selection_previous"
lvim.builtin.telescope.defaults.mappings.n["<C-q>"]["1"] = "smart_send_to_qflist"
lvim.builtin.telescope.defaults.mappings.n["<C-q>"]["2"] = "open_qflist"
lvim.builtin.telescope.defaults.path_display.shorten = 5
lvim.builtin.telescope.defaults.prompt_prefix = " "
-- lvim.builtin.telescope.defaults.qflist_previewer = function ()
lvim.builtin.telescope.defaults.selection_caret = " "
lvim.builtin.telescope.defaults.selection_strategy = "reset"
lvim.builtin.telescope.defaults.set_env.COLORTERM = "truecolor"
lvim.builtin.telescope.defaults.sorting_strategy = "descending"
lvim.builtin.telescope.defaults.use_less = true
lvim.builtin.telescope.defaults.winblend = 0
lvim.builtin.telescope.extensions.fzy_native.override_file_sorter = true
lvim.builtin.telescope.extensions.fzy_native.override_generic_sorter = false
lvim.builtin.terminal.active = true
lvim.builtin.terminal.close_on_exit = true
lvim.builtin.terminal.direction = "float"
lvim.builtin.terminal.execs["1"]["1"] = "lazygit"
lvim.builtin.terminal.execs["1"]["2"] = "gg"
lvim.builtin.terminal.execs["1"]["3"] = "LazyGit"
lvim.builtin.terminal.float_opts.border = "curved"
lvim.builtin.terminal.float_opts.highlights.background = "Normal"
lvim.builtin.terminal.float_opts.highlights.border = "Normal"
lvim.builtin.terminal.float_opts.winblend = 0
lvim.builtin.terminal.hide_numbers = true
lvim.builtin.terminal.insert_mappings = true
lvim.builtin.terminal.open_mapping = "<c-t>"
lvim.builtin.terminal.persist_size = false
lvim.builtin.terminal.shade_terminals = true
lvim.builtin.terminal.shading_factor = 2
lvim.builtin.terminal.shell = "/usr/bin/zsh"
lvim.builtin.terminal.size = 20
lvim.builtin.terminal.start_in_insert = true
lvim.builtin.treesitter.autotag.enable = false
lvim.builtin.treesitter.context_commentstring.config.css = "// %s"
lvim.builtin.treesitter.context_commentstring.enable = false
lvim.builtin.treesitter.ensure_installed["10"] = "graphql"
lvim.builtin.treesitter.ensure_installed["11"] = "c_sharp"
lvim.builtin.treesitter.ensure_installed["12"] = "css"
lvim.builtin.treesitter.ensure_installed["13"] = "cpp"
lvim.builtin.treesitter.ensure_installed["14"] = "cmake"
lvim.builtin.treesitter.ensure_installed["15"] = "html"
lvim.builtin.treesitter.ensure_installed["16"] = "java"
lvim.builtin.treesitter.ensure_installed["17"] = "python"
lvim.builtin.treesitter.ensure_installed["18"] = "vim"
lvim.builtin.treesitter.ensure_installed["19"] = "json"
lvim.builtin.treesitter.ensure_installed["1"] = "json"
lvim.builtin.treesitter.ensure_installed["20"] = "yaml"
lvim.builtin.treesitter.ensure_installed["21"] = "typescript"
lvim.builtin.treesitter.ensure_installed["22"] = "tsx"
lvim.builtin.treesitter.ensure_installed["2"] = "bash"
lvim.builtin.treesitter.ensure_installed["3"] = "dot"
lvim.builtin.treesitter.ensure_installed["4"] = "lua"
lvim.builtin.treesitter.ensure_installed["5"] = "go"
lvim.builtin.treesitter.ensure_installed["6"] = "rust"
lvim.builtin.treesitter.ensure_installed["7"] = "yaml"
lvim.builtin.treesitter.ensure_installed["8"] = "javascript"
lvim.builtin.treesitter.ensure_installed["9"] = "dockerfile"
lvim.builtin.treesitter.highlight.additional_vim_regex_highlighting = true
lvim.builtin.treesitter.highlight.disable["1"] = "latex"
lvim.builtin.treesitter.highlight.enable = true
lvim.builtin.treesitter.indent.disable["1"] = "yaml"
lvim.builtin.treesitter.indent.enable = true
lvim.builtin.treesitter.matchup.enable = false
lvim.builtin.treesitter.playground.enable = false
lvim.builtin.treesitter.playground.keybindings.focus_language = "f"
lvim.builtin.treesitter.playground.keybindings.goto_node = "<cr>"
lvim.builtin.treesitter.playground.keybindings.show_help = "?"
lvim.builtin.treesitter.playground.keybindings.toggle_anonymous_nodes = "a"
lvim.builtin.treesitter.playground.keybindings.toggle_hl_groups = "i"
lvim.builtin.treesitter.playground.keybindings.toggle_injected_languages = "t"
lvim.builtin.treesitter.playground.keybindings.toggle_language_display = "I"
lvim.builtin.treesitter.playground.keybindings.toggle_query_editor = "o"
lvim.builtin.treesitter.playground.keybindings.unfocus_language = "F"
lvim.builtin.treesitter.playground.keybindings.update = "R"
lvim.builtin.treesitter.playground.persist_queries = false
lvim.builtin.treesitter.playground.updatetime = 25
lvim.builtin.treesitter.rainbow.enable = false
lvim.builtin.treesitter.rainbow.extended_mode = true
lvim.builtin.treesitter.rainbow.max_file_lines = 1000
lvim.builtin.treesitter.textobjects.select.enable = false
lvim.builtin.treesitter.textobjects.swap.enable = false
lvim.builtin.treesitter.textsubjects.enable = false
lvim.builtin.treesitter.textsubjects.keymaps[";"] = "textsubjects-big"
lvim.builtin.treesitter.textsubjects.keymaps["."] = "textsubjects-smart"
lvim.builtin.which_key.active = true
lvim.builtin.which_key.mappings["/"]["1"] = "<cmd>CommentToggle<CR>"
lvim.builtin.which_key.mappings[";"]["1"] = "<cmd>Dashboard<CR>"
lvim.builtin.which_key.mappings["/"]["2"] = "Comment"
lvim.builtin.which_key.mappings[";"]["2"] = "Dashboard"
lvim.builtin.which_key.mappings.b.b["1"] = "<cmd>b#<cr>"
lvim.builtin.which_key.mappings.b.b["2"] = "Previous"
lvim.builtin.which_key.mappings.b.D["1"] = "<cmd>BufferOrderByDirectory<cr>"
lvim.builtin.which_key.mappings.b.D["2"] = "Sort by directory"
lvim.builtin.which_key.mappings.b.e["1"] = "<cmd>BufferCloseAllButCurrent<cr>"
lvim.builtin.which_key.mappings.b.e["2"] = "Close all but current"
lvim.builtin.which_key.mappings.b.f["1"] = "<cmd>Telescope buffers<cr>"
lvim.builtin.which_key.mappings.b.f["2"] = "Find"
lvim.builtin.which_key.mappings.b.h["1"] = "<cmd>BufferCloseBuffersLeft<cr>"
lvim.builtin.which_key.mappings.b.h["2"] = "Close all to the left"
lvim.builtin.which_key.mappings.b.j["1"] = "<cmd>BufferPick<cr>"
lvim.builtin.which_key.mappings.b.j["2"] = "Jump"
lvim.builtin.which_key.mappings.b.l["1"] = "<cmd>BufferCloseBuffersRight<cr>"
lvim.builtin.which_key.mappings.b.L["1"] = "<cmd>BufferOrderByLanguage<cr>"
lvim.builtin.which_key.mappings.b.l["2"] = "Close all to the right"
lvim.builtin.which_key.mappings.b.L["2"] = "Sort by language"
lvim.builtin.which_key.mappings.b.name = "Buffers"
lvim.builtin.which_key.mappings.b.w["1"] = "<cmd>BufferWipeout<cr>"
lvim.builtin.which_key.mappings.b.w["2"] = "Wipeout"
lvim.builtin.which_key.mappings.c["1"] = "<cmd>BufferClose!<CR>"
lvim.builtin.which_key.mappings.c["2"] = "Close Buffer"
lvim.builtin.which_key.mappings.d.b["1"] = "<cmd>lua require'dap'.step_back()<cr>"
lvim.builtin.which_key.mappings.d.b["2"] = "Step Back"
lvim.builtin.which_key.mappings.d.c["1"] = "<cmd>lua require'dap'.continue()<cr>"
lvim.builtin.which_key.mappings.d.C["1"] = "<cmd>lua require'dap'.run_to_cursor()<cr>"
lvim.builtin.which_key.mappings.d.c["2"] = "Continue"
lvim.builtin.which_key.mappings.d.C["2"] = "Run To Cursor"
lvim.builtin.which_key.mappings.d.d["1"] = "<cmd>lua require'dap'.disconnect()<cr>"
lvim.builtin.which_key.mappings.d.d["2"] = "Disconnect"
lvim.builtin.which_key.mappings.d.g["1"] = "<cmd>lua require'dap'.session()<cr>"
lvim.builtin.which_key.mappings.d.g["2"] = "Get Session"
lvim.builtin.which_key.mappings.d.i["1"] = "<cmd>lua require'dap'.step_into()<cr>"
lvim.builtin.which_key.mappings.d.i["2"] = "Step Into"
lvim.builtin.which_key.mappings.d.name = "Debug"
lvim.builtin.which_key.mappings.d.o["1"] = "<cmd>lua require'dap'.step_over()<cr>"
lvim.builtin.which_key.mappings.d.o["2"] = "Step Over"
lvim.builtin.which_key.mappings.d.p["1"] = "<cmd>lua require'dap'.pause.toggle()<cr>"
lvim.builtin.which_key.mappings.d.p["2"] = "Pause"
lvim.builtin.which_key.mappings.d.q["1"] = "<cmd>lua require'dap'.close()<cr>"
lvim.builtin.which_key.mappings.d.q["2"] = "Quit"
lvim.builtin.which_key.mappings.d.r["1"] = "<cmd>lua require'dap'.repl.toggle()<cr>"
lvim.builtin.which_key.mappings.d.r["2"] = "Toggle Repl"
lvim.builtin.which_key.mappings.d.s["1"] = "<cmd>lua require'dap'.continue()<cr>"
lvim.builtin.which_key.mappings.d.s["2"] = "Start"
lvim.builtin.which_key.mappings.d.t["1"] = "<cmd>lua require'dap'.toggle_breakpoint()<cr>"
lvim.builtin.which_key.mappings.d.t["2"] = "Toggle Breakpoint"
lvim.builtin.which_key.mappings.d.u["1"] = "<cmd>lua require'dap'.step_out()<cr>"
lvim.builtin.which_key.mappings.d.u["2"] = "Step Out"
lvim.builtin.which_key.mappings.e["1"] = "<cmd>NvimTreeToggle<CR>"
lvim.builtin.which_key.mappings.e["2"] = "Explorer"
lvim.builtin.which_key.mappings.f["1"] = "<cmd>Telescope find_files<CR>"
lvim.builtin.which_key.mappings.f["2"] = "Find File"
lvim.builtin.which_key.mappings.g.b["1"] = "<cmd>Telescope git_branches<cr>"
lvim.builtin.which_key.mappings.g.b["2"] = "Checkout branch"
lvim.builtin.which_key.mappings.g.C["1"] = "<cmd>Telescope git_bcommits<cr>"
lvim.builtin.which_key.mappings.g.c["1"] = "<cmd>Telescope git_commits<cr>"
lvim.builtin.which_key.mappings.g.c["2"] = "Checkout commit"
lvim.builtin.which_key.mappings.g.C["2"] = "Checkout commit(for current file)"
lvim.builtin.which_key.mappings.g.d["1"] = "<cmd>Gitsigns diffthis HEAD<cr>"
lvim.builtin.which_key.mappings.g.d["2"] = "Git Diff"
lvim.builtin.which_key.mappings.gg = "LazyGit"
lvim.builtin.which_key.mappings.g.j["1"] = "<cmd>lua require 'gitsigns'.next_hunk()<cr>"
lvim.builtin.which_key.mappings.g.j["2"] = "Next Hunk"
lvim.builtin.which_key.mappings.g.k["1"] = "<cmd>lua require 'gitsigns'.prev_hunk()<cr>"
lvim.builtin.which_key.mappings.g.k["2"] = "Prev Hunk"
lvim.builtin.which_key.mappings.g.l["1"] = "<cmd>lua require 'gitsigns'.blame_line()<cr>"
lvim.builtin.which_key.mappings.g.l["2"] = "Blame"
lvim.builtin.which_key.mappings.g.name = "Git"
lvim.builtin.which_key.mappings.g.o["1"] = "<cmd>Telescope git_status<cr>"
lvim.builtin.which_key.mappings.g.o["2"] = "Open changed file"
lvim.builtin.which_key.mappings.g.p["1"] = "<cmd>lua require 'gitsigns'.preview_hunk()<cr>"
lvim.builtin.which_key.mappings.g.p["2"] = "Preview Hunk"
lvim.builtin.which_key.mappings.g.R["1"] = "<cmd>lua require 'gitsigns'.reset_buffer()<cr>"
lvim.builtin.which_key.mappings.g.r["1"] = "<cmd>lua require 'gitsigns'.reset_hunk()<cr>"
lvim.builtin.which_key.mappings.g.R["2"] = "Reset Buffer"
lvim.builtin.which_key.mappings.g.r["2"] = "Reset Hunk"
lvim.builtin.which_key.mappings.g.s["1"] = "<cmd>lua require 'gitsigns'.stage_hunk()<cr>"
lvim.builtin.which_key.mappings.g.s["2"] = "Stage Hunk"
lvim.builtin.which_key.mappings.g.u["1"] = "<cmd>lua require 'gitsigns'.undo_stage_hunk()<cr>"
lvim.builtin.which_key.mappings.g.u["2"] = "Undo Stage Hunk"
lvim.builtin.which_key.mappings.h["1"] = "<cmd>nohlsearch<CR>"
lvim.builtin.which_key.mappings.h["2"] = "No Highlight"
lvim.builtin.which_key.mappings.l.a["1"] = "<cmd>lua require('core.telescope').code_actions()<cr>"
lvim.builtin.which_key.mappings.l.a["2"] = "Code Action"
lvim.builtin.which_key.mappings.L.c["1"] = "<cmd>edit/home/crash/.config/lvim/config.lua<cr>"
lvim.builtin.which_key.mappings.L.c["2"] = "Edit config.lua"
lvim.builtin.which_key.mappings.l.d["1"] = "<cmd>Telescope lsp_document_diagnostics<cr>"
lvim.builtin.which_key.mappings.l.d["2"] = "Document Diagnostics"
lvim.builtin.which_key.mappings.L.f["1"] = "<cmd>lua require('core.telescope').find_lunarvim_files()<cr>"
lvim.builtin.which_key.mappings.l.f["1"] = "<cmd>lua vim.lsp.buf.formatting()<cr>"
lvim.builtin.which_key.mappings.L.f["2"] = "Find LunarVim files"
lvim.builtin.which_key.mappings.l.f["2"] = "Format"
lvim.builtin.which_key.mappings.L.g["1"] = "<cmd>lua require('core.telescope').grep_lunarvim_files()<cr>"
lvim.builtin.which_key.mappings.L.g["2"] = "Grep LunarVim files"
lvim.builtin.which_key.mappings.l.i["1"] = "<cmd>LspInfo<cr>"
lvim.builtin.which_key.mappings.l.I["1"] = "<cmd>LspInstallInfo<cr>"
lvim.builtin.which_key.mappings.L.i["1"] = "<cmd>lua require('core.info').toggle_popup(vim.bo.filetype)<cr>"
lvim.builtin.which_key.mappings.L.I["1"] = "<cmd>lua require('core.telescope').view_lunarvim_changelog()<cr>"
lvim.builtin.which_key.mappings.l.i["2"] = "Info"
lvim.builtin.which_key.mappings.l.I["2"] = "Installer Info"
lvim.builtin.which_key.mappings.L.i["2"] = "Toggle LunarVim Info"
lvim.builtin.which_key.mappings.L.I["2"] = "View LunarVim's changelog"
lvim.builtin.which_key.mappings.l.j["1"] = "<cmd>lua vim.lsp.diagnostic.goto_next({popup_opts = {border = lvim.lsp.popup_border}})<cr>"
lvim.builtin.which_key.mappings.l.j["2"] = "Next Diagnostic"
lvim.builtin.which_key.mappings.L.k["1"] = "<cmd>lua require('keymappings').print()<cr>"
lvim.builtin.which_key.mappings.l.k["1"] = "<cmd>lua vim.lsp.diagnostic.goto_prev({popup_opts = {border = lvim.lsp.popup_border}})<cr>"
lvim.builtin.which_key.mappings.l.k["2"] = "Prev Diagnostic"
lvim.builtin.which_key.mappings.L.k["2"] = "View LunarVim's default keymappings"
lvim.builtin.which_key.mappings.l.l["1"] = "<cmd>lua vim.lsp.codelens.run()<cr>"
lvim.builtin.which_key.mappings.l.l["2"] = "CodeLens Action"
lvim.builtin.which_key.mappings.L.l.d["1"] = "<cmd>lua require('core.terminal').toggle_log_view(require('core.log').get_path())<cr>"
lvim.builtin.which_key.mappings.L.l.D["1"] = "<cmd>lua vim.fn.execute('edit ' .. require('core.log').get_path())<cr>"
lvim.builtin.which_key.mappings.L.l.D["2"] = "Open the default logfile"
lvim.builtin.which_key.mappings.L.l.d["2"] = "view default log"
lvim.builtin.which_key.mappings.L.l.l["1"] = "<cmd>lua require('core.terminal').toggle_log_view(vim.lsp.get_log_path())<cr>"
lvim.builtin.which_key.mappings.L.l.L["1"] = "<cmd>lua vim.fn.execute('edit ' .. vim.lsp.get_log_path())<cr>"
lvim.builtin.which_key.mappings.L.l.L["2"] = "Open the LSP logfile"
lvim.builtin.which_key.mappings.L.l.l["2"] = "view lsp log"
lvim.builtin.which_key.mappings.L.l.N["1"] = "<cmd>edit $NVIM_LOG_FILE<cr>"
lvim.builtin.which_key.mappings.L.l.n["1"] = "<cmd>lua require('core.terminal').toggle_log_view(os.getenv('NVIM_LOG_FILE'))<cr>"
lvim.builtin.which_key.mappings.L.l.N["2"] = "Open the Neovim logfile"
lvim.builtin.which_key.mappings.L.l.n["2"] = "view neovim log"
lvim.builtin.which_key.mappings.L.l.name = "+logs"
lvim.builtin.which_key.mappings.L.l.P["1"] = "<cmd>exe 'edit '.stdpath('cache').'/packer.nvim.log'<cr>"
lvim.builtin.which_key.mappings.L.l.p["1"] = "<cmd>lua require('core.terminal').toggle_log_view('packer.nvim')<cr>"
lvim.builtin.which_key.mappings.L.l.P["2"] = "Open the Packer logfile"
lvim.builtin.which_key.mappings.L.l.p["2"] = "view packer log"
lvim.builtin.which_key.mappings.l.name = "LSP"
lvim.builtin.which_key.mappings.L.name = "+LunarVim"
lvim.builtin.which_key.mappings.l.p.d["1"] = "<cmd>lua require('lsp.peek').Peek('definition')<cr>"
lvim.builtin.which_key.mappings.l.p.d["2"] = "Definition"
lvim.builtin.which_key.mappings.l.p.i["1"] = "<cmd>lua require('lsp.peek').Peek('implementation')<cr>"
lvim.builtin.which_key.mappings.l.p.i["2"] = "Implementation"
lvim.builtin.which_key.mappings.l.p.name = "Peek"
lvim.builtin.which_key.mappings.l.p.t["1"] = "<cmd>lua require('lsp.peek').Peek('typeDefinition')<cr>"
lvim.builtin.which_key.mappings.l.p.t["2"] = "Type Definition"
lvim.builtin.which_key.mappings.l.q["1"] = "<cmd>lua vim.lsp.diagnostic.set_loclist()<cr>"
lvim.builtin.which_key.mappings.l.q["2"] = "Quickfix"
lvim.builtin.which_key.mappings.L.r["1"] = "<cmd>lua require('utils').reload_lv_config()<cr>"
lvim.builtin.which_key.mappings.l.r["1"] = "<cmd>lua vim.lsp.buf.rename()<cr>"
lvim.builtin.which_key.mappings.L.r["2"] = "Reload configurations"
lvim.builtin.which_key.mappings.l.r["2"] = "Rename"
lvim.builtin.which_key.mappings.l.s["1"] = "<cmd>Telescope lsp_document_symbols<cr>"
lvim.builtin.which_key.mappings.l.S["1"] = "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>"
lvim.builtin.which_key.mappings.l.s["2"] = "Document Symbols"
lvim.builtin.which_key.mappings.l.S["2"] = "Workspace Symbols"
lvim.builtin.which_key.mappings.L.u["1"] = "<cmd>LvimUpdate<cr>"
lvim.builtin.which_key.mappings.L.u["2"] = "Update LunarVim"
lvim.builtin.which_key.mappings.l.w["1"] = "<cmd>Telescope lsp_workspace_diagnostics<cr>"
lvim.builtin.which_key.mappings.l.w["2"] = "Workspace Diagnostics"
lvim.builtin.which_key.mappings.p.c["1"] = "<cmd>PackerCompile<cr>"
lvim.builtin.which_key.mappings.p.c["2"] = "Compile"
lvim.builtin.which_key.mappings.p.i["1"] = "<cmd>PackerInstall<cr>"
lvim.builtin.which_key.mappings.p.i["2"] = "Install"
lvim.builtin.which_key.mappings.p.name = "Packer"
lvim.builtin.which_key.mappings.p.r["1"] = "<cmd>lua require('utils').reload_lv_config()<cr>"
lvim.builtin.which_key.mappings.p.r["2"] = "Reload"
lvim.builtin.which_key.mappings.p.S["1"] = "<cmd>PackerStatus<cr>"
lvim.builtin.which_key.mappings.p.s["1"] = "<cmd>PackerSync<cr>"
lvim.builtin.which_key.mappings.p.S["2"] = "Status"
lvim.builtin.which_key.mappings.p.s["2"] = "Sync"
lvim.builtin.which_key.mappings.p.u["1"] = "<cmd>PackerUpdate<cr>"
lvim.builtin.which_key.mappings.p.u["2"] = "Update"
lvim.builtin.which_key.mappings.q["1"] = "<cmd>q!<CR>"
lvim.builtin.which_key.mappings.q["2"] = "Quit"
lvim.builtin.which_key.mappings.s.b["1"] = "<cmd>Telescope git_branches<cr>"
lvim.builtin.which_key.mappings.s.b["2"] = "Checkout branch"
lvim.builtin.which_key.mappings.s.c["1"] = "<cmd>Telescope colorscheme<cr>"
lvim.builtin.which_key.mappings.s.C["1"] = "<cmd>Telescope commands<cr>"
lvim.builtin.which_key.mappings.s.c["2"] = "Colorscheme"
lvim.builtin.which_key.mappings.s.C["2"] = "Commands"
lvim.builtin.which_key.mappings.s.f["1"] = "<cmd>Telescope find_files<cr>"
lvim.builtin.which_key.mappings.s.f["2"] = "Find File"
lvim.builtin.which_key.mappings.s.h["1"] = "<cmd>Telescope help_tags<cr>"
lvim.builtin.which_key.mappings.s.h["2"] = "Find Help"
lvim.builtin.which_key.mappings.s.k["1"] = "<cmd>Telescope keymaps<cr>"
lvim.builtin.which_key.mappings.s.k["2"] = "Keymaps"
lvim.builtin.which_key.mappings.s.M["1"] = "<cmd>Telescope man_pages<cr>"
lvim.builtin.which_key.mappings.s.M["2"] = "Man Pages"
lvim.builtin.which_key.mappings.s.name = "Search"
lvim.builtin.which_key.mappings.s.p["1"] = "<cmd>lua require('telescope.builtin.internal').colorscheme({enable_preview = true})<cr>"
lvim.builtin.which_key.mappings.s.p["2"] = "Colorscheme with Preview"
lvim.builtin.which_key.mappings.s.r["1"] = "<cmd>Telescope oldfiles<cr>"
lvim.builtin.which_key.mappings.s.R["1"] = "<cmd>Telescope registers<cr>"
lvim.builtin.which_key.mappings.s.r["2"] = "Open Recent File"
lvim.builtin.which_key.mappings.s.R["2"] = "Registers"
lvim.builtin.which_key.mappings.s.t["1"] = "<cmd>Telescope live_grep<cr>"
lvim.builtin.which_key.mappings.s.t["2"] = "Text"
lvim.builtin.which_key.mappings.T.i["1"] = ":TSConfigInfo<cr>"
lvim.builtin.which_key.mappings.T.i["2"] = "Info"
lvim.builtin.which_key.mappings.T.name = "Treesitter"
lvim.builtin.which_key.mappings.w["1"] = "<cmd>w!<CR>"
lvim.builtin.which_key.mappings.w["2"] = "Save"
lvim.builtin.which_key.opts.mode = "n"
lvim.builtin.which_key.opts.noremap = true
lvim.builtin.which_key.opts.nowait = true
lvim.builtin.which_key.opts.prefix = "<leader>"
lvim.builtin.which_key.opts.silent = true
lvim.builtin.which_key.setup.hidden["1"] = "<silent>"
lvim.builtin.which_key.setup.hidden["2"] = "<cmd>"
lvim.builtin.which_key.setup.hidden["3"] = "<Cmd>"
lvim.builtin.which_key.setup.hidden["4"] = "<CR>"
lvim.builtin.which_key.setup.hidden["5"] = "call"
lvim.builtin.which_key.setup.hidden["6"] = "lua"
lvim.builtin.which_key.setup.hidden["7"] = "^:"
lvim.builtin.which_key.setup.hidden["8"] = "^ "
lvim.builtin.which_key.setup.icons.breadcrumb = "»"
lvim.builtin.which_key.setup.icons.group = "+"
lvim.builtin.which_key.setup.icons.separator = "➜"
lvim.builtin.which_key.setup.layout.height.max = 25
lvim.builtin.which_key.setup.layout.height.min = 4
lvim.builtin.which_key.setup.layout.spacing = 3
lvim.builtin.which_key.setup.layout.width.max = 50
lvim.builtin.which_key.setup.layout.width.min = 20
lvim.builtin.which_key.setup.plugins.marks = true
lvim.builtin.which_key.setup.plugins.presets.g = true
lvim.builtin.which_key.setup.plugins.presets.motions = false
lvim.builtin.which_key.setup.plugins.presets.nav = true
lvim.builtin.which_key.setup.plugins.presets.operators = false
lvim.builtin.which_key.setup.plugins.presets.text_objects = false
lvim.builtin.which_key.setup.plugins.presets.windows = true
lvim.builtin.which_key.setup.plugins.presets.z = true
lvim.builtin.which_key.setup.plugins.registers = true
lvim.builtin.which_key.setup.plugins.spelling.enabled = true
lvim.builtin.which_key.setup.plugins.spelling.suggestions = 20
lvim.builtin.which_key.setup.show_help = true
lvim.builtin.which_key.setup.window.border = "single"
lvim.builtin.which_key.setup.window.margin["1"] = 1
lvim.builtin.which_key.setup.window.margin["2"] = 0
lvim.builtin.which_key.setup.window.margin["3"] = 1
lvim.builtin.which_key.setup.window.margin["4"] = 0
lvim.builtin.which_key.setup.window.padding["1"] = 2
lvim.builtin.which_key.setup.window.padding["2"] = 2
lvim.builtin.which_key.setup.window.padding["3"] = 2
lvim.builtin.which_key.setup.window.padding["4"] = 2
lvim.builtin.which_key.setup.window.position = "bottom"
lvim.builtin.which_key.vmappings["/"]["1"] = ":CommentToggle<CR>"
lvim.builtin.which_key.vmappings["/"]["2"] = "Comment"
lvim.builtin.which_key.vopts.mode = "v"
lvim.builtin.which_key.vopts.noremap = true
lvim.builtin.which_key.vopts.nowait = true
lvim.builtin.which_key.vopts.prefix = "<leader>"
lvim.builtin.which_key.vopts.silent = true
lvim.colorscheme = "onedarker"
lvim.database.auto_execute = 1
lvim.database.save_location = "/home/crash/.config/lunarvim_db"
lvim.format_on_save = true
lvim.keys.command_mode["<C-j>"]["1"] = "pumvisible() ? \"\\<C-n>\" : \"\\<C-j>\""
lvim.keys.command_mode["<C-j>"]["2"].expr = true
lvim.keys.command_mode["<C-j>"]["2"].noremap = true
lvim.keys.command_mode["<C-k>"]["1"] = "pumvisible() ? \"\\<C-p>\" : \"\\<C-k>\""
lvim.keys.command_mode["<C-k>"]["2"].expr = true
lvim.keys.command_mode["<C-k>"]["2"].noremap = true
lvim.keys.insert_mode["<A-Down>"] = "<C-\\><C-N><C-w>j"
lvim.keys.insert_mode["<A-j>"] = "<Esc>:m .+1<CR>==gi"
lvim.keys.insert_mode["<A-k>"] = "<Esc>:m .-2<CR>==gi"
lvim.keys.insert_mode["<A-Left>"] = "<C-\\><C-N><C-w>h"
lvim.keys.insert_mode["<A-Right>"] = "<C-\\><C-N><C-w>l"
lvim.keys.insert_mode["<A-Up>"] = "<C-\\><C-N><C-w>k"
lvim.keys.insert_mode["<C-j>"]["1"] = "pumvisible() ? \"\\<down>\" : \"\\<C-j>\""
lvim.keys.insert_mode["<C-j>"]["2"].expr = true
lvim.keys.insert_mode["<C-j>"]["2"].noremap = true
lvim.keys.insert_mode["<C-k>"]["1"] = "pumvisible() ? \"\\<up>\" : \"\\<C-k>\""
lvim.keys.insert_mode["<C-k>"]["2"].expr = true
lvim.keys.insert_mode["<C-k>"]["2"].noremap = true
lvim.keys.insert_mode.jj = "<ESC>"
lvim.keys.insert_mode.jk = "<ESC>"
lvim.keys.insert_mode.kj = "<ESC>"
lvim.keys.normal_mode["<A-j>"] = ":m .+1<CR>=="
lvim.keys.normal_mode["<A-k>"] = ":m .-2<CR>=="
lvim.keys.normal_mode["<C-Down>"] = ":resize +2<CR>"
lvim.keys.normal_mode["<C-h>"] = "<C-w>h"
lvim.keys.normal_mode["<C-j>"] = "<C-w>j"
lvim.keys.normal_mode["<C-k>"] = "<C-w>k"
lvim.keys.normal_mode["<C-l>"] = "<C-w>l"
lvim.keys.normal_mode["<C-Left>"] = ":vertical resize -2<CR>"
lvim.keys.normal_mode["<C-q>"] = ":call QuickFixToggle()<CR>"
lvim.keys.normal_mode["<C-Right>"] = ":vertical resize +2<CR>"
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["<C-Up>"] = ":resize -2<CR>"
lvim.keys.normal_mode["]q"] = ":cnext<CR>"
lvim.keys.normal_mode["[q"] = ":cprev<CR>"
lvim.keys.normal_mode["<S-h>"] = ":BufferPrevious<CR>"
lvim.keys.normal_mode["<S-l>"] = ":BufferNext<CR>"
lvim.keys.term_mode["<C-h>"] = "<C-\\><C-N><C-w>h"
lvim.keys.term_mode["<C-j>"] = "<C-\\><C-N><C-w>j"
lvim.keys.term_mode["<C-k>"] = "<C-\\><C-N><C-w>k"
lvim.keys.term_mode["<C-l>"] = "<C-\\><C-N><C-w>l"
lvim.keys.visual_block_mode["<A-j>"] = ":m '>+1<CR>gv-gv"
lvim.keys.visual_block_mode["<A-k>"] = ":m '<-2<CR>gv-gv"
lvim.keys.visual_block_mode.J = ":move '>+1<CR>gv-gv"
lvim.keys.visual_block_mode.K = ":move '<-2<CR>gv-gv"
lvim.keys.visual_mode["<"] = "<gv"
lvim.keys.visual_mode[">"] = ">gv"
lvim.leader = "space"
lvim.line_wrap_cursor_movement = true
lvim.lint_on_save = true
lvim.log.level = "warn"
lvim.log.viewer.cmd = "lnav"
lvim.log.viewer.layout_config.direction = "horizontal"
lvim.log.viewer.layout_config.open_mapping = ""
lvim.log.viewer.layout_config.size = 40
lvim.lsp.automatic_servers_installation = true
lvim.lsp.buffer_mappings.normal_mode.gD["1"] = "<cmd>lua vim.lsp.buf.declaration()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gd["1"] = "<cmd>lua vim.lsp.buf.definition()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gD["2"] = "Goto declaration"
lvim.lsp.buffer_mappings.normal_mode.gd["2"] = "Goto Definition"
lvim.lsp.buffer_mappings.normal_mode.gI["1"] = "<cmd>lua vim.lsp.buf.implementation()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gI["2"] = "Goto Implementation"
lvim.lsp.buffer_mappings.normal_mode.gl["1"] = "<cmd>lua require'lsp.handlers'.show_line_diagnostics()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gl["2"] = "Show line diagnostics"
lvim.lsp.buffer_mappings.normal_mode.gp["1"] = "<cmd>lua require'lsp.peek'.Peek('definition')<CR>"
lvim.lsp.buffer_mappings.normal_mode.gp["2"] = "Peek definition"
lvim.lsp.buffer_mappings.normal_mode.gr["1"] = "<cmd>lua vim.lsp.buf.references()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gr["2"] = "Goto references"
lvim.lsp.buffer_mappings.normal_mode.gs["1"] = "<cmd>lua vim.lsp.buf.signature_help()<CR>"
lvim.lsp.buffer_mappings.normal_mode.gs["2"] = "show signature help"
lvim.lsp.buffer_mappings.normal_mode.K["1"] = "<cmd>lua vim.lsp.buf.hover()<CR>"
lvim.lsp.buffer_mappings.normal_mode.K["2"] = "Show hover"
lvim.lsp.code_lens_refresh = true
lvim.lsp.diagnostics.severity_sort = true
lvim.lsp.diagnostics.signs.active = true
lvim.lsp.diagnostics.signs.values["1"].name = "LspDiagnosticsSignError"
lvim.lsp.diagnostics.signs.values["1"].text = ""
lvim.lsp.diagnostics.signs.values["2"].name = "LspDiagnosticsSignWarning"
lvim.lsp.diagnostics.signs.values["2"].text = ""
lvim.lsp.diagnostics.signs.values["3"].name = "LspDiagnosticsSignHint"
lvim.lsp.diagnostics.signs.values["3"].text = ""
lvim.lsp.diagnostics.signs.values["4"].name = "LspDiagnosticsSignInformation"
lvim.lsp.diagnostics.signs.values["4"].text = ""
lvim.lsp.diagnostics.underline = true
lvim.lsp.diagnostics.update_in_insert = false
lvim.lsp.diagnostics.virtual_text = true
lvim.lsp.document_highlight = true
lvim.lsp.popup_border = "single"
lvim.lsp.templates_dir = "/home/crash/.local/share/lunarvim/site/after/ftplugin"
lvim.transparent_window = false
lvim.vsnip_dir = "/home/crash/.config/snippets"
